-- secret :: (Int -> a) -> a
-- secret f = f <number>
--
-- where <number> -- any number in range of Int
--
--
--
-- secret2 :: (Int -> Bool) -> Bool
-- secret2 f = True
--
-- secret2 :: (Int -> Bool) -> Bool
-- secret2 f = False
--
-- Any of secret realizations
