-- secret :: (Int -> a) -> a
-- secret f = f <number>
--
-- where <number> -- any number in range of Int
--
--
--
-- secret2 :: (Int -> Bool) -> Bool
-- secret2 f = True
--
-- secret2 :: (Int -> Bool) -> Bool
-- secret2 f = False
--
-- Any of secret realizations
--
-- boolFunction :: Bool -> Bool -> Bool
--
-- secret2 :: (Int -> Bool) -> Bool
-- secret2 f = fold boolFunction [secretI f, secretJ f, ...]
--
--
-- where secretI, secretJ are like secret
